# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_url_queriedat'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
