# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-23 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_url_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='dns',
            field=models.TextField(blank=True, null=True),
        ),
    ]
