# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-02 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_dnsrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsnRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rawRecord', models.TextField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asns', to='core.Url')),
            ],
        ),
        migrations.AlterField(
            model_name='dnsrecord',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dnsRecords', to='core.Url'),
        ),
    ]
