# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-06 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20160202_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhoisRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rawRecord', models.TextField(blank=True, null=True)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whois', to='core.Url')),
            ],
        ),
    ]
