# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-06 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_whoisrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='asnrecord',
            name='source',
            field=models.CharField(default='asn', max_length=256),
            preserve_default=False,
        ),
    ]
